{
  name: "Nightly build",
  on: {
    schedule: [
      # build at ~00:05 PT daily (startup delays may affect that)
      { cron: "05 17 * * *" }
    ]
  },
  jobs: {
    publish: {
      runs-on: "ubuntu-latest",
      steps: [
        {
          uses: "actions/checkout@v2",
          with: {
            fetch-depth: 2
          }
        },
        {
          id: "commits_since_last_nightly",
          name: "Check for commits since last night's build",
          run: "test -n \"$(git log --oneline --since '25 hours ago')\"",
          continue-on-error: true
        },
        {
          name: "Set up node 12",
          uses: "actions/setup-node@v1",
          if: "${{ job.commits_since_last_nightly.outcome == 'success' }}",
          with: {
            registry-url: "https://registry.npmjs.com",
            node-version: "12"
          }
        },
        {
          run: "yarn",
          if: "${{ job.commits_since_last_nightly.outcome == 'success' }}"
        },
        {
          run: "yarn prepublishOnly",
          if: "${{ job.commits_since_last_nightly.outcome == 'success' }}",
        },
      ]
    }
  }
}

